=== netvirus/reb_h5_storm/rebellion_h5_realm/dist/gameserver/config/premium/premiumSystemOptionsData.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="premium" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rates" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:float" name="expRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="spRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="dropRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="dropChance" use="optional"/>
                                            <xs:attribute type="xs:float" name="dropAmount" use="optional"/>
                                            <xs:attribute type="xs:float" name="spoilRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="spoilChance" use="optional"/>
                                            <xs:attribute type="xs:float" name="spoilAmount" use="optional"/>
                                            <xs:attribute type="xs:float" name="adenaDropRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="weightLimitRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="craftChance" use="optional"/>
                                            <xs:attribute type="xs:float" name="mCraftChance" use="optional"/>
                                            <xs:attribute type="xs:float" name="doubleCraftChance" use="optional"/>
                                            <xs:attribute type="xs:float" name="extractableRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="questDropRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="questRewardRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="petExpRate" use="optional"/>
                                            <xs:attribute type="xs:float" name="raidDropChance" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="time">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:byte" name="days" use="optional"/>
                                            <xs:attribute type="xs:byte" name="hours" use="optional"/>
                                            <xs:attribute type="xs:byte" name="minutes" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:int" name="itemId" use="optional"/>
                                            <xs:attribute type="xs:byte" name="itemAmount" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id" use="optional"/>
                        <xs:attribute type="xs:string" name="name" use="optional"/>
                        <xs:attribute type="xs:string" name="icon" use="optional"/>
                        <xs:attribute type="xs:string" name="aura" use="optional"/>
                        <xs:attribute type="xs:string" name="main" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== netvirus/reb_h5_storm/rebellion_h5_realm/dist/gameserver/config/premium/premiumSystemOptionsData.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="premiumSystemOptionsData.xsd">
	<premium id="1" name="Premium subscription for 1 day" icon="branchsys2.br_vitality_day_i00" aura="false" main="true">
		<rates expRate="2." spRate="2." dropRate="1." dropChance="2." dropAmount="1." spoilRate="2." spoilChance="2." spoilAmount="1." adenaDropRate="2." weightLimitRate="2." craftChance="2." mCraftChance="2." extractableRate="2." manorDropRate="2." questDropRate="2." petExpRate="2." raidDropChance="2." raidDropAmount="2." herbDropChance="2." herbDropAmount="1." />
		<time days="1" hours="0" minutes="0"/>
		<price itemId="4037" itemAmount="1"/>
	</premium>
	<premium id="2" name="Premium subscription for 7 days" icon="branchsys2.br_vitality_day_i00" aura="false" main="true">
		<rates expRate="2." spRate="2." dropRate="1." dropChance="2." dropAmount="1." spoilRate="2." spoilChance="2." spoilAmount="1." adenaDropRate="2." weightLimitRate="2." craftChance="2." mCraftChance="2." extractableRate="2." manorDropRate="2." questDropRate="2." petExpRate="2." raidDropChance="2." raidDropAmount="2." herbDropChance="2." herbDropAmount="1." />
		<time days="7" hours="0" minutes="0"/>
		<price itemId="4037" itemAmount="5"/>
	</premium>
	<premium id="3" name="Premium subscription for 30 days" icon="branchsys2.br_vitality_day_i00" aura="false" main="true">
		<rates expRate="2." spRate="2." dropRate="1." dropChance="2." dropAmount="1." spoilRate="2." spoilChance="2." spoilAmount="1." adenaDropRate="2." weightLimitRate="2." craftChance="2." mCraftChance="2." extractableRate="2." manorDropRate="2." questDropRate="2." petExpRate="2." raidDropChance="2." raidDropAmount="2." herbDropChance="2." herbDropAmount="1." />
		<time days="30" hours="0" minutes="0"/>
		<price itemId="4037" itemAmount="10"/>
	</premium>
	<premium id="4" name="Premium subscription for 1 hour - Super pumping" icon="branchsys2.br_vitality_day_i00" aura="true" main="false">
		<rates expRate="3." spRate="3." dropRate="1." dropChance="1." dropAmount="1." spoilRate="1." spoilChance="1." spoilAmount="1." adenaDropRate="1." weightLimitRate="1." craftChance="1." mCraftChance="1." extractableRate="1." manorDropRate="1." questDropRate="1." petExpRate="3." raidDropChance="1." raidDropAmount="1." herbDropChance="1." herbDropAmount="1." />
		<time days="0" hours="1" minutes="0"/>
		<price itemId="4037" itemAmount="2"/>
	</premium>
	<premium id="5" name="Premium subscription for 1 hour - Super spoil" icon="branchsys2.br_vitality_day_i00" aura="true" main="false">
		<rates expRate="1." spRate="1." dropRate="1." dropChance="1." dropAmount="1." spoilRate="3." spoilChance="3." spoilAmount="2." adenaDropRate="1." weightLimitRate="3." craftChance="1." mCraftChance="1." extractableRate="1." manorDropRate="1." questDropRate="1." petExpRate="1." raidDropChance="1." raidDropAmount="1." herbDropChance="1." herbDropAmount="1." />
		<time days="0" hours="1" minutes="0"/>
		<price itemId="4037" itemAmount="2"/>
	</premium>
	<premium id="6" name="Premium subscription for 1 hour - Super drop" icon="branchsys2.br_vitality_day_i00" aura="true" main="false">
		<rates expRate="1." spRate="1." dropRate="3." dropChance="3." dropAmount="2." spoilRate="1." spoilChance="1." spoilAmount="1." adenaDropRate="1." weightLimitRate="3." craftChance="1." mCraftChance="1." extractableRate="1." manorDropRate="1." questDropRate="1." petExpRate="1." raidDropChance="1." raidDropAmount="1." herbDropChance="1." herbDropAmount="1." />
		<time days="0" hours="1" minutes="0"/>
		<price itemId="4037" itemAmount="2"/>
	</premium>
	<premium id="7" name="Premium subscription for 1 hour - Super craft" icon="branchsys2.br_vitality_day_i00" aura="true" main="false">
		<rates expRate="1." spRate="1." dropRate="1." dropChance="1." dropAmount="1." spoilRate="1." spoilChance="1." spoilAmount="1." adenaDropRate="1." weightLimitRate="3." craftChance="3." mCraftChance="3." extractableRate="1." manorDropRate="1." questDropRate="1." petExpRate="1." raidDropChance="1." raidDropAmount="1." herbDropChance="1." herbDropAmount="1." />
		<time days="0" hours="1" minutes="0"/>
		<price itemId="4037" itemAmount="2"/>
	</premium>
</list>
